platform :ios, '9.0'

use_frameworks!
target 'SwiftSeek' do

pod 'Alamofire', '~> 4.8.1'
pod 'SwiftyJSON', '~> 4.2.0'
pod 'RxSwift', '~> 4.4.0'
pod 'RxCocoa', '~> 4.4.0'
pod 'PromiseKit', '~> 6.7.0'
pod 'NVActivityIndicatorView', '~> 4.4.0'
pod 'SkeletonView', '~> 1.4.2'
pod 'Hero', '~> 1.4.0'
pod 'SwiftEntryKit', '0.8.8'
pod 'Toast-Swift', '~> 4.0.1'
pod 'SKPhotoBrowser', '~> 6.0.0'
pod 'RealmSwift', '~> 3.13.1'
pod 'IQKeyboardManagerSwift', '~> 6.2.0'
pod 'Kingfisher', '~> 4.10.1'
pod 'Timepiece', '~> 1.3.1'

end
